name: blog-publish-github-action
on: [push, workflow_dispatch]
jobs:
  blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Donwloading Code
        uses: actions/checkout@v2
      - name: Running Hello World
        run: echo "Hello"
      - name: Use blog publish github action
        uses: aru31/blog-publish-action@master
