name: blog-publish-github-action
on: [push, workflow_dispatch]
jobs:
  devto-blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Use blog publish github action for devto
        uses: aru31/blog-publish-action@master
        with: 
          website: "devto"
          token_github: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.DEVTO_TOKEN }}
  medium-blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Use blog publish github action for medium
        uses: aru31/blog-publish-action@master
        with: 
          website: "medium"
          token_github: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.MEDIUM_TOKEN }}
