name: blog-publish-github-action
on: [push, workflow_dispatch]
jobs:
  blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Donwloading Code
      - uses: actions/checkout@v2
      - run: echo "Hello"
