name: blog-publish-github-action
on: [push, workflow_dispatch]
jobs:
  devto-blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Use blog publish github action for devto
        uses: aru31/blog-publish-action@master
        with: 
          website: "devto"
          log_level: "debug"
          token: ${{ secrets.DEVTO_TOKEN }}
          
  medium-blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Use blog publish github action for medium
        uses: aru31/blog-publish-action@master
        with: 
          website: "medium"
          log_level: "debug"
          token: ${{ secrets.MEDIUM_TOKEN }}

  hashnode-blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Use blog publish github action for hashnode
        uses: aru31/blog-publish-action@master
        with: 
          website: "hashnode"
          log_level: "debug"
          token: ${{ secrets.HASHNODE_TOKEN }}